# stage 1: build binary
FROM golang:1.17-buster as build

# Create and change to the app directory.
WORKDIR /app

# Retrieve application dependencies.
# This allows the container build to reuse cached dependencies.
# Expecting to copy go.mod and if present go.sum.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY . ./

# build the binary
RUN make build

# stage 2: launch binary
FROM alpine:3.14 AS run

# set environmental variable
ARG ENVIRONMENT="local"
ENV ENVIRONMENT=$ENVIRONMENT

# Create and change to the app directory.
WORKDIR /app

RUN apk add --no-cache bash

# Copy binary from the build layer to this layer
COPY --from=build /app/dist/main .
COPY --from=build /app/test/wait-for-service.sh .
COPY --from=build /app/config/$ENVIRONMENT.yaml config/$ENVIRONMENT.yaml

EXPOSE 8080
CMD ["/app/main"]
